[project]
name = "web"
version = "0.1.0"
description = ""
authors = [
    {name = "Ulises Rabasa",email = "rabasaulises@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flask>=2.0.0",
    "python-dotenv",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.poetry]
packages = [{include = "web", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
